export const DEMO_ITEMS_V35 = [
  {
    id: "live-1",
    title: "Arena Sports HD",
    section: "live",
    category: "Sport",
    badge: "Live",
    year: "2026",
    duration: "Live",
    rating: "0+",
    progress: 18,
    description: "Sportkanal als Demo.",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    cover: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "live-2",
    title: "Blue Coast News",
    section: "live",
    category: "News",
    badge: "News",
    year: "2026",
    duration: "Live",
    rating: "0+",
    progress: 8,
    description: "Nachrichtenkanal als Demo.",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    cover: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "movie-1",
    title: "Neon Nights",
    section: "movie",
    category: "Sci-Fi",
    badge: "Trailer",
    year: "2026",
    duration: "2h 01m",
    rating: "16+",
    progress: 62,
    description: "Atmosphaerischer Sci-Fi-Thriller.",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    cover: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "movie-2",
    title: "Glass Horizon",
    section: "movie",
    category: "Drama",
    badge: "Top",
    year: "2025",
    duration: "1h 48m",
    rating: "12+",
    progress: 88,
    description: "Premium-Film als Demo.",
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    cover: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "series-1",
    title: "Dark Signal",
    section: "series",
    category: "Thriller",
    badge: "Neu",
    year: "2026",
    duration: "8 Folgen",
    rating: "12+",
    progress: 41,
    description: "Serien-Demo mit starkem Stil.",
    streamUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    cover: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "series-2",
    title: "Retro Circuit",
    section: "series",
    category: "Tech",
    badge: "Kult",
    year: "2024",
    duration: "12 Folgen",
    rating: "12+",
    progress: 29,
    description: "Nostalgische Tech-Serie.",
    streamUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    cover: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
  },
];

export const DEFAULT_PROFILES_V35 = [
  { id: "p1", name: "Sven", emoji: "TV" },
  { id: "p2", name: "Gast", emoji: "Play" },
  { id: "p3", name: "Kids", emoji: "Kids" },
];

export const DEFAULT_SETTINGS_V35 = {
  autoplay: true,
  autosave: true,
  compactMode: false,
  adultFilter: false,
  connectionMode: "auto",
};

export const DEMO_EPG_V35 = [
  { id: "e1", channel: "Arena Sports HD", time: "18:00", title: "Topspiel Live" },
  { id: "e2", channel: "Arena Sports HD", time: "20:15", title: "Analyse Extra" },
  { id: "e3", channel: "Blue Coast News", time: "19:00", title: "Abendnachrichten" },
  { id: "e4", channel: "Blue Coast News", time: "20:00", title: "Weltblick" },
];
